### ISSUE TITLE
Sigue funcionando?

### ISSUE THREAD

**Issue by azohc** [ricardojoserf/spotify-playlist-downloader#1]
Me ha saltado el siguiente error: 
`os.system('cd results && instantmusic -s "'+wholename.encode('utf-8')+'" -q  > /dev/null 2>&1')
TypeError: must be str, not bytes`
No se si lo arregla pero añadiendo `.decode('utf-8')` a `wholename.encode('utf-8')` evitaba el error. 
He seguido toods los pasos y no consigo descargar nada :(

**Comment by Javisalva9** [comment]
A mi la última vez que no me hacía nada fue por la dependencia de _instantmusic_.
Prueba a hacer `instantmusic -s algunaCancion` a ver si te salta algún fallo.
En mi caso tuve que actualizar otra dependencia _youtube-dl_ `sudo pip install -U youtube-dl`

**Comment by azohc** [comment]
No parece que se me esté instalando instantmusic... 
Lo he instalado con "exito" en pip pero luego no puedo tirar instantmusic desde el shell de bash. Todo esto con dependencias instaladas y probando en un shell nuevo.. por si acaso.
[final del log de sudo pip install instantmusic](https://imgur.com/a/PxsoQur)

**Comment by ricardojoserf** [comment]
Hola @azohc , hemos cambiado toda la funcionalidad del programa gracias a un nuevo colaborador, ahora funciona sin problema. Cualquier problema que te surja con esta nueva versión dinos y reabrimos el issue. 
Cualquier cosa nos dices ;)
