### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by askfriends** [ricardojoserf/spotify-playlist-downloader#4]
## Expected vs Actual Behavior
when i run this command

`!python3 main.py -u 0AFu117j8WX2auNWDAyMMV?si=z5Yp3ki8SjGxogCQifD7Jg -i c24dfe3e7cad4888ab96600000000 -s ba6325e2ebc040ab963560000000 -d /content`

i recieve this error

`Downloading songs...

Traceback (most recent call last):
  File "main.py", line 135, in <module>
    main()
  File "main.py", line 131, in main
    download_songs(json.loads(result))
  File "main.py", line 47, in download_songs
    for item in spotify_info["items"]:
KeyError: 'items'`

Note: in above id and secret, i have removed last characters for safety.
here is the link for playlist that i am trying to download
https://open.spotify.com/playlist/0AFu117j8WX2auNWDAyMMV?si=z5Yp3ki8SjGxogCQifD7Jg

## Specifications
google colab
 - Operative system:
google colab
 - Version (e.g. Python version):
google colab has latest version

## Steps to Reproduce the Problem
go to colab.google.com sign in with your gmail, create new notebook than follow steps given in this repo

**Comment by ricardojoserf** [comment]
Hi @askfriends !!! Could you try with any of these two options:

```
python3 main.py -u spotify:playlist:0AFu117j8WX2auNWDAyMMV -i $CLIENT_ID -s $CLIENT_SECRET -d results1
```

```
python3 main.py -p 0AFu117j8WX2auNWDAyMMV -i $CLIENT_ID -s $CLIENT_SECRET -d results2
```

I think that could be the mistake in this case, the last part "?si=..." and that "-u" is for the uri and "-p" for the id. It is working locally for me, let me know if it works now for you so I can close the issue ;)

Regards,

Ricardo

**Comment by askfriends** [comment]
> s

tried both commands but getting same error.
btw here is the albym uri that i tried now
spotify:album:1lxIcjl8Aa4Zvjec4ceMxR

**Comment by ricardojoserf** [comment]
Hi @askfriends. In this new case with the new URI I get that error too because it is an album, not a playlist :P (I run "python3 main.py -p 1lxIcjl8Aa4Zvjec4ceMxR -i $CLIENT_ID -s $CLIENT_SECRET -d results3").
 
The error is due to the program not calculating any song in the playlist, so please check:
- We are using the id of a playlist (for example, "-p 0AFu117j8WX2auNWDAyMMV" should work)
- The cliend id and client secret are correct (I can't send you mine xDD)

Also I am unable to access collab google, I do not know if the access is restricted to some countries.

**Comment by askfriends** [comment]
> Hi @askfriends. In this new case with the new URI I get that error too because it is an album, not a playlist :P (I run "python3 main.py -p 1lxIcjl8Aa4Zvjec4ceMxR -i $CLIENT_ID -s $CLIENT_SECRET -d results3").
> 
> The error is due to the program not calculating any song in the playlist, so please check:
> 
> * We are using the id of a playlist (for example, "-p 0AFu117j8WX2auNWDAyMMV" should work)
> * The cliend id and client secret are correct (I can't send you mine xDD)
> 
> Also I am unable to access collab google, I do not know if the access is restricted to some countries.

i dont know if its country specific, btw you can try vpn

yeah i just created new playlist from album and it now downloading...thanks

btw can we set output quality to 320kbps?

also downloaded files has tag or id in the last,  for example
/content/Abhi Na Jao Chhod Kar (Revival) - Asha Bhosle - Mohd. Rafi - Hum Dono [1961]-HaxOAMa6uVY.mp3

notice the last characters, they are available [diferent for each song] in all songs, how to disable that?

**Comment by ricardojoserf** [comment]
Hi @askfriends ,

The vpn part is true but for using Google products which are working only in the US (I do not know if that is the case), I would need an account verified with a US phone number :P 

Regarding the quality, the script tries to download the 320 Kbps version (in line 78, "'preferredquality': '320'"). You can check more options here - https://github.com/ytdl-org/youtube-dl , you should change the object ydl_opts in line 68.

About the id part that is true, I think chess-seventh added that functionality and I deleted in a commit after his/her pull request (my bad, I will try to fix that).

Regards,

Ricardo

**Comment by askfriends** [comment]
> Hi @askfriends ,
> 
> The vpn part is true but for using Google products which are working only in the US (I do not know if that is the case), I would need an account verified with a US phone number :P
> 
> Regarding the quality, the script tries to download the 320 Kbps version (in line 78, "'preferredquality': '320'"). You can check more options here - https://github.com/ytdl-org/youtube-dl , you should change the object ydl_opts in line 68.
> 
> About the id part that is true, I think chess-seventh added that functionality and I deleted in a commit after his/her pull request (my bad, I will try to fix that).
> 
> Regards,
> 
> Ricardo

Thanks for your time..its clarifies everything.
one last question though..this script downloads from spotify itself or its downloads from youtube and merge metadata from spotify?

**Comment by ricardojoserf** [comment]
Hi! It gets the list of songs from the Spotify API and downloads them with youtube-dl (https://github.com/ytdl-org/youtube-dl)

Regards,

Ricardo

**Comment by askfriends** [comment]
> Hi! It gets the list of songs from the Spotify API and downloads them with youtube-dl (https://github.com/ytdl-org/youtube-dl)
> 
> Regards,
> 
> Ricardo

i see..it means if songs are not available on youtube than we cant downoad them, right?

and btw i just noticed that downloaded files dont have metadata i-e artist name, album cover etc

**Comment by ricardojoserf** [comment]
Hi! Yes, you are correct. And I do not know about the metadata, it will depend on the functionality of youtube-dl. Feel free to create a pull request with that functionality to this repo or youtube-dl ;)

Regards,

Ricardo

**Comment by askfriends** [comment]
> Hi! Yes, you are correct. And I do not know about the metadata, it will depend on the functionality of youtube-dl. Feel free to create a pull request with that functionality to this repo or youtube-dl ;)
> 
> Regards,
> 
> Ricardo

im not pro, but there are several repos available here on github which gets metadata from spotify and merge them after downloading from youtube-dl. have a look at them and try to implement that in your code.

**Comment by ricardojoserf** [comment]
Hi @askfriends ! Thank you for the idea, maybe we will try to implement it in the future if we have time. Anyways if you have time to do it and you feel like it, it is not necessary to be a pro, just making the effort!! 
I will close the issue now, if you find an error or have new suggestions feel free to open new issues ;)
